In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [3]:
df = pd.read_csv("../data/processed_data/clean_data.csv")

In [4]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
numerical_col = [col for col in df.columns if df[col].dtype in ["int64",float]]
categorical_col = [col for col in df.columns if df[col].nunique()>1 and df[col].dtype == "str" and col != "Churn"]

In [6]:
print(numerical_col)
print(categorical_col)

['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

In [7]:
df[numerical_col].head()

   SeniorCitizen  tenure  MonthlyCharges  TotalCharges
0              0       1           29.85         29.85
1              0      34           56.95       1889.50
2              0       2           53.85        108.15
3              0      45           42.30       1840.75
4              0       2           70.70        151.65

### Scaling

In [8]:
scaler = StandardScaler()
df_scale = pd.DataFrame(
    scaler.fit_transform(df[numerical_col]),
    columns= scaler.get_feature_names_out(numerical_col),
    index= df.index
)

### Encoding

In [9]:
encode = OneHotEncoder(handle_unknown="ignore",sparse_output=False)
df_encode = pd.DataFrame(
    encode.fit_transform(df[categorical_col]),
    columns= encode.get_feature_names_out(categorical_col),
    index= df.index
    )

In [10]:
df_encode.head()

,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,PhoneService_Yes,MultipleLines_No,MultipleLines_No phone service,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [11]:
final_train_df = pd.concat([df_scale,df_encode,df["Churn"]],axis=1)

In [12]:
final_train_df["Churn"] = final_train_df["Churn"].str.strip().str.lower()

final_train_df["Churn"] = final_train_df["Churn"].apply(lambda x: 1 if x == "yes" else 0)

In [13]:
final_train_df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn
0,-0.439916,-1.277445,-1.160323,-0.994971,1.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0
1,-0.439916,0.066327,-0.259629,-0.173876,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0
2,-0.439916,-1.236724,-0.362660,-0.960399,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1
3,-0.439916,0.514251,-0.746535,-0.195400,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0
4,-0.439916,-1.236724,0.197365,-0.941193,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1

In [14]:
final_train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 46 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   SeniorCitizen                            7043 non-null   float64
 1   tenure                                   7043 non-null   float64
 2   MonthlyCharges                           7043 non-null   float64
 3   TotalCharges                             7043 non-null   float64
 4   gender_Female                            7043 non-null   float64
 5   gender_Male                              7043 non-null   float64
 6   Partner_No                               7043 non-null   float64
 7   Partner_Yes                              7043 non-null   float64
 8   Dependents_No                            7043 non-null   float64
 9   Dependents_Yes                           7043 non-null   float64
 10  PhoneService_No                          7043 non-null   float64
 11  PhoneService_Yes                         7043 non-null   float64
 12  MultipleLines_No                         7043 non-null   float64
 13  MultipleLines_No phone service           7043 non-null   float64
 14  MultipleLines_Yes                        7043 non-null   float64
 15  InternetService_DSL                      7043 non-null   float64
 16  InternetService_Fiber optic              7043 non-null   float64
 17  InternetService_No                       7043 non-null   float64
 18  OnlineSecurity_No                        7043 non-null   float64
 19  OnlineSecurity_No internet service       7043 non-null   float64
 20  OnlineSecurity_Yes                       7043 non-null   float64
 21  OnlineBackup_No                          7043 non-null   float64
 22  OnlineBackup_No internet service         7043 non-null   float64
 23  OnlineBackup_Yes                         7043 non-null   float64
 24  DeviceProtection_No                      7043 non-null   float64
 25  DeviceProtection_No internet service     7043 non-null   float64
 26  DeviceProtection_Yes                     7043 non-null   float64
 27  TechSupport_No                           7043 non-null   float64
 28  TechSupport_No internet service          7043 non-null   float64
 29  TechSupport_Yes                          7043 non-null   float64
 30  StreamingTV_No                           7043 non-null   float64
 31  StreamingTV_No internet service          7043 non-null   float64
 32  StreamingTV_Yes                          7043 non-null   float64
 33  StreamingMovies_No                       7043 non-null   float64
 34  StreamingMovies_No internet service      7043 non-null   float64
 35  StreamingMovies_Yes                      7043 non-null   float64
 36  Contract_Month-to-month                  7043 non-null   float64
 37  Contract_One year                        7043 non-null   float64
 38  Contract_Two year                        7043 non-null   float64
 39  PaperlessBilling_No                      7043 non-null   float64
 40  PaperlessBilling_Yes                     7043 non-null   float64
 41  PaymentMethod_Bank transfer (automatic)  7043 non-null   float64
 42  PaymentMethod_Credit card (automatic)    7043 non-null   float64
 43  PaymentMethod_Electronic check           7043 non-null   float64
 44  PaymentMethod_Mailed check               7043 non-null   float64
 45  Churn                                    7043 non-null   int64
dtypes: float64(45), int64(1)
memory usage: 2.5 MB

### NOW all Features (columns) convert to either Int OR Float

In [15]:
final_train_df.to_csv("../data/processed_data/feature_train.csv", index=False)